pipeline {
    agent {
        docker {
                image "python:3.9.13"
                args "-u root"
            }
    }
    parameters {
        string(
            name: "TEXT",
            description: "The text which you want to convert into QR-code.",
            defaultValue: "http://localhost:8080/",
        )
        string(
            name: "FILE_NAME",
            description: "The file name of output QR code: ${FILE_NAME}.png.",
            defaultValue: "output",
        )
    }
    stages {
        stage("git-clone") {
            steps {
                sh """
                    if [ -d ./qrcode-script ]; then
                        cd ./qrcode-script
                        git pull
                    else
                        git clone https://github.com/takahiroaoki/qrcode-script.git
                    fi
                """
            }
        }
        stage("build") {
            steps {
                sh """
                    cd ./qrcode-script/app
                    pip install qrcode[pil]==7.3.1
                    python ./src/make_qrcode.py
                """
            }
            post {
                always {
                    echo "========== Build Finished =========="
                }
                success {
                    archiveArtifacts artifacts: "qrcode-script/app/output/${FILE_NAME}.png"
                    echo "========== The pipeline has executed successfully. =========="
                }
                failure {
                    echo "========== The pipeline has executed in failure. =========="
                }
                unstable {
                    echo "========== The build of pipeline is unstable. =========="
                }
            }
        }
    }
}